runtime: nodejs12
env: standard

env_variables:
  GCLOUD_VISION_DESTINATION_PATH: '/tmp/gcloud-vision-uploads'

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
