version: "3"
services:
  app:
    build: .
    container_name: app
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    environment:
      - MONGODB_URI=mongodb://mongo/nest
    depends_on:
      - mongo
    links:
      - mongo
    command: yarn dev
  
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    command: mongod