version: "3"
services:
  app:
    build: .
    container_name: app
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    environment:
      - MONGODB_URI=mongodb://mongo/nest
    depends_on:
      - mongo
    links:
      - mongo
      - mysql
    command: yarn dev
  
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    command: mongod

  mysql:
    build: ./mysql
    container_name: mysql
    volumes:
      - ./mysql/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test